version: "3"
services:
  database:
    image: postgres
    env_file:
      - .env
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./pg:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
    networks:
      - network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: 12345
    volumes:
      - ./pg:/root/.pgadmin
    ports:
      - "5431:80"
    networks:
      - network
    restart: always

networks:
  network:
    driver: bridge
